# Generated by Django 5.0.6 on 2024-07-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0002_alter_recipe_ingredients_alter_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
